name: Release

on:
  push:
    paths:
      - 'app/version.py'

permissions:
  contents: write

env:
  QT_QPA_PLATFORM: offscreen 

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build application
        working-directory: ./app
        run: |
          pyinstaller --name=yt-dlp-gui --clean -y app.py --icon ./ui/assets/yt-dlp-gui.ico --noconsole
          Compress-Archive -Path dist/* -DestinationPath yt-dlp-gui-win64.zip
      - uses: actions/upload-artifact@v2
        with:
          name: yt-dlp-gui-win
          path: ./app/yt-dlp-gui-win64.zip

  github-release:
    name: github-release
    runs-on: ubuntu-latest
    needs:
      - build-windows
    steps:
      - uses: actions/checkout@v3

      - name: Restore windows build
        uses: actions/download-artifact@v3
        with:
          name: yt-dlp-gui-win
          path: /opt/builds

      - name: Get version
        run: echo "VERSION=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' ./app/version.py)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            /opt/builds/yt-dlp-gui-win64.zip