name: Release

on:
  push:
    paths:
      - 'app/version.py'

permissions:
  contents: write

env:
  QT_QPA_PLATFORM: offscreen 

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update -y
        sudo apt-get install -y libegl1-mesa libegl1-mesa-dev '^libxcb.*-dev' libx11-xcb-dev \
        libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev 
    - name: Build application
      working-directory: ./app
      run: |
        pyinstaller --name=yt-dlp-gui --clean -y app.py
        zip -r yt-dlp-gui-linux64.zip dist/*
    - uses: actions/upload-artifact@v2
      with:
        name: yt-dlp-gui-linux
        path: ./app/yt-dlp-gui-linux64.zip

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build application
        working-directory: ./app
        run: |
          pyinstaller --name=yt-dlp-gui --clean -y app.py --icon ./ui/assets/yt-dlp-gui.ico --noconsole
          Compress-Archive -Path dist/* -DestinationPath yt-dlp-gui-win64.zip
      - uses: actions/upload-artifact@v2
        with:
          name: yt-dlp-gui-win
          path: ./app/yt-dlp-gui-win64.zip

  github-release:
    name: github-release
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-windows
    steps:
      - uses: actions/checkout@v3
      - name: Restore linux build
        uses: actions/download-artifact@v3
        with:
          name: yt-dlp-gui-linux
          path: /opt/builds

      - name: Restore windows build
        uses: actions/download-artifact@v3
        with:
          name: yt-dlp-gui-win
          path: /opt/builds

      - name: Get version
        run: echo "VERSION=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' ./app/version.py)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            /opt/builds/yt-dlp-gui-linux64.zip
            /opt/builds/yt-dlp-gui-win64.zip